In [9]:
# libraries
import pandas as pd
import numpy as np

In [2]:
# c.Since = "2012-11-30 - 2013-01-01"

df = pd.read_csv("sandy_one_year.csv")

/Users/emmalimoli/opt/anaconda3/envs/PythonData/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3071: DtypeWarning: Columns (22) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [4]:
df.head(10)

,id,conversation_id,created_at,date,time,timezone,user_id,username,name,place,...,geo,source,user_rt_id,user_rt,retweet_id,reply_to,retweet_date,translate,trans_src,trans_dest
0,285535700277919744,285535700277919744,2012-12-30 18:59:50 EST,2012-12-30,18:59:50,-500,820741129,rosieemordi,Rosemary Emordi,NaN,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
1,285535644325916673,285535644325916673,2012-12-30 18:59:37 EST,2012-12-30,18:59:37,-500,331809661,ellenbarr1,Ellen Barr,NaN,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
2,285535639317905408,285535639317905408,2012-12-30 18:59:36 EST,2012-12-30,18:59:36,-500,80220290,dirty_diana29,D!@Π@™,NaN,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
3,285535540563030018,285535540563030018,2012-12-30 18:59:12 EST,2012-12-30,18:59:12,-500,43477325,ecobard,Grumpy Old Antifa,NaN,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
4,285535505096003584,285535505096003584,2012-12-30 18:59:04 EST,2012-12-30,18:59:04,-500,35017099,paulbarer,Norm Feeney,NaN,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
5,285535350787538944,285535350787538944,2012-12-30 18:58:27 EST,2012-12-30,18:58:27,-500,23043604,derekandming,Derek and Ming,NaN,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
6,285535263206297602,285535263206297602,2012-12-30 18:58:06 EST,2012-12-30,18:58:06,-500,135191649,mandelamen,Mahari Mengistu,NaN,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
7,285535012785377280,285535012785377280,2012-12-30 18:57:06 EST,2012-12-30,18:57:06,-500,265270727,nassauctynews,Nassau County News,NaN,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
8,285534983261655040,285529721851240448,2012-12-30 18:56:59 EST,2012-12-30,18:56:59,-500,52220507,jweisel,Jessica Weisel,NaN,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
9,285534953700225024,285534953700225024,2012-12-30 18:56:52 EST,2012-12-30,18:56:52,-500,35017099,paulbarer,Norm Feeney,NaN,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN

In [5]:
# check columns
df.columns

Index(['id', 'conversation_id', 'created_at', 'date', 'time', 'timezone',
       'user_id', 'username', 'name', 'place', 'tweet', 'language', 'mentions',
       'urls', 'photos', 'replies_count', 'retweets_count', 'likes_count',
       'hashtags', 'cashtags', 'link', 'retweet', 'quote_url', 'video',
       'thumbnail', 'near', 'geo', 'source', 'user_rt_id', 'user_rt',
       'retweet_id', 'reply_to', 'retweet_date', 'translate', 'trans_src',
       'trans_dest'],
      dtype='object')

In [6]:
# count rows
df.count()

id                 472291
conversation_id    472291
created_at         472291
date               472291
time               472291
timezone           472291
user_id            472291
username           472291
name               472205
place                6389
tweet              472291
language           472291
mentions           472291
urls               472291
photos             472291
replies_count      472291
retweets_count     472291
likes_count        472291
hashtags           472291
cashtags           472291
link               472291
retweet            472291
quote_url              68
video              472291
thumbnail           10688
near                    0
geo                     0
source                  0
user_rt_id              0
user_rt                 0
retweet_id              0
reply_to           472291
retweet_date            0
translate               0
trans_src               0
trans_dest              0
dtype: int64

In [7]:
# check types
df.dtypes

id                   int64
conversation_id      int64
created_at          object
date                object
time                object
timezone             int64
user_id              int64
username            object
name                object
place               object
tweet               object
language            object
mentions            object
urls                object
photos              object
replies_count        int64
retweets_count       int64
likes_count          int64
hashtags            object
cashtags            object
link                object
retweet               bool
quote_url           object
video                int64
thumbnail           object
near               float64
geo                float64
source             float64
user_rt_id         float64
user_rt            float64
retweet_id         float64
reply_to            object
retweet_date       float64
translate          float64
trans_src          float64
trans_dest         float64
dtype: object

In [8]:
# id, conversation_id, created_at, date, time, user_id, username, name  
# place, tweet, language, mentions,urls, photos, replies_count, retweets_count     
# likes_count, hashtags, cashtags, link, retweet, quote_url, video, thumbnail, reply_to  

df1 = df[['id', 
         'conversation_id', 
         'created_at', 
         'date', 
         'time', 
         'user_id', 
         'username', 
         'name', 
         'place', 
         'tweet', 
         'language', 
         'mentions',
         'urls', 
         'photos', 
         'replies_count', 
         'retweets_count',     
         'likes_count', 
         'hashtags', 
         'cashtags', 
         'link', 
         'retweet', 
         'quote_url', 
         'video', 
         'thumbnail', 
         'reply_to']]
df1.head()

,id,conversation_id,created_at,date,time,user_id,username,name,place,tweet,...,retweets_count,likes_count,hashtags,cashtags,link,retweet,quote_url,video,thumbnail,reply_to
0,285535700277919744,285535700277919744,2012-12-30 18:59:50 EST,2012-12-30,18:59:50,820741129,rosieemordi,Rosemary Emordi,NaN,"Looked on a magazine and said ""awe these littl...",...,0,0,['sad'],[],https://twitter.com/RosieEmordi/status/2855357...,False,NaN,0,NaN,[]
1,285535644325916673,285535644325916673,2012-12-30 18:59:37 EST,2012-12-30,18:59:37,331809661,ellenbarr1,Ellen Barr,NaN,The headlines move on but it's only been a few...,...,0,1,['sandyhook'],[],https://twitter.com/EllenBarr1/status/28553564...,False,NaN,0,NaN,[]
2,285535639317905408,285535639317905408,2012-12-30 18:59:36 EST,2012-12-30,18:59:36,80220290,dirty_diana29,D!@Π@™,NaN,PTA in Connecticut is collecting snowflakes f...,...,0,0,[],[],https://twitter.com/dirty_diana29/status/28553...,False,NaN,0,NaN,[]
3,285535540563030018,285535540563030018,2012-12-30 18:59:12 EST,2012-12-30,18:59:12,43477325,ecobard,Grumpy Old Antifa,NaN,Will climate change ever have its Sandy Hook m...,...,0,0,[],[],https://twitter.com/ecobard/status/28553554056...,False,NaN,0,NaN,[]
4,285535505096003584,285535505096003584,2012-12-30 18:59:04 EST,2012-12-30,18:59:04,35017099,paulbarer,Norm Feeney,NaN,@kathleenmadigan If the photos of the dead chi...,...,0,0,[],[],https://twitter.com/PaulBarer/status/285535505...,False,NaN,0,NaN,[]

In [20]:
# pick dates between a few days before and a few days after the event, set date to index

new_in = df1.set_index('date')
new_in

,id,conversation_id,created_at,time,user_id,username,name,place,tweet,language,...,retweets_count,likes_count,hashtags,cashtags,link,retweet,quote_url,video,thumbnail,reply_to
date,,,,,,,,,,,,,,,,,,,,,
2012-12-30,285535700277919744,285535700277919744,2012-12-30 18:59:50 EST,18:59:50,820741129,rosieemordi,Rosemary Emordi,NaN,"Looked on a magazine and said ""awe these littl...",en,...,0,0,['sad'],[],https://twitter.com/RosieEmordi/status/2855357...,False,NaN,0,NaN,[]
2012-12-30,285535644325916673,285535644325916673,2012-12-30 18:59:37 EST,18:59:37,331809661,ellenbarr1,Ellen Barr,NaN,The headlines move on but it's only been a few...,en,...,0,1,['sandyhook'],[],https://twitter.com/EllenBarr1/status/28553564...,False,NaN,0,NaN,[]
2012-12-30,285535639317905408,285535639317905408,2012-12-30 18:59:36 EST,18:59:36,80220290,dirty_diana29,D!@Π@™,NaN,PTA in Connecticut is collecting snowflakes f...,en,...,0,0,[],[],https://twitter.com/dirty_diana29/status/28553...,False,NaN,0,NaN,[]
2012-12-30,285535540563030018,285535540563030018,2012-12-30 18:59:12 EST,18:59:12,43477325,ecobard,Grumpy Old Antifa,NaN,Will climate change ever have its Sandy Hook m...,en,...,0,0,[],[],https://twitter.com/ecobard/status/28553554056...,False,NaN,0,NaN,[]
2012-12-30,285535505096003584,285535505096003584,2012-12-30 18:59:04 EST,18:59:04,35017099,paulbarer,Norm Feeney,NaN,@kathleenmadigan If the photos of the dead chi...,en,...,0,0,[],[],https://twitter.com/PaulBarer/status/285535505...,False,NaN,0,NaN,[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2012-11-29,274338676509667330,274338676509667330,2012-11-29 21:26:52 EST,21:26:52,42679281,qtl13,QuaDaisha Lowery,NaN,I hate Sandy Hook/Mtp! I wish i was still live...,en,...,0,0,[],[],https://twitter.com/qtl13/status/2743386765096...,False,NaN,0,NaN,[]
2012-11-29,274336188482072577,274325383116107776,2012-11-29 21:16:58 EST,21:16:58,540212597,lee_david_k,David Lee,NaN,@tpmcminn @FatouSadio @caitlinso @Kantrowitz T...,en,...,0,0,[],[],https://twitter.com/Lee_David_K/status/2743361...,False,NaN,0,NaN,[]
2012-11-29,274322556746612737,274322556746612737,2012-11-29 20:22:48 EST,20:22:48,168009390,recruitingtape,Patrick Toland,NaN,New Lacrosse Recruiting Tape: Sophomore Kristi...,en,...,0,0,[],[],https://twitter.com/recruitingtape/status/2743...,False,NaN,0,NaN,[]
2012-11-29,274321735174725632,274321735174725632,2012-11-29 20:19:32 EST,20:19:32,168009390,recruitingtape,Patrick Toland,NaN,New Lacrosse Highlight Film: Cassie Ekstrom. S...,en,...,0,0,[],[],https://twitter.com/recruitingtape/status/2743...,False,NaN,0,NaN,[]
2012-11-29,274313175527198720,274313175527198720,2012-11-29 19:45:32 EST,19:45:32,526262414,coraaw26,Cora Canty,NaN,How do I get WGH20226 Sandy Hook Lighthouse Li...,en,...,0,0,['sales'],[],https://twitter.com/Coraaw26/status/2743131755...,False,NaN,0,NaN,[]

In [30]:
# choose dates the week of the event
dates_bet = new_in[(new_in.index > '2012-12-11') & (new_in.index <= '2012-12-17')]
dates_bet

,id,conversation_id,created_at,time,user_id,username,name,place,tweet,language,...,retweets_count,likes_count,hashtags,cashtags,link,retweet,quote_url,video,thumbnail,reply_to
date,,,,,,,,,,,,,,,,,,,,,
2012-12-17,280900174006595584,280900174006595584,2012-12-17 23:59:55 EST,23:59:55,166259681,examinecharlott,Examine Charlotte,NaN,Singers on ‘The Voice’ perform ‘Hallelujah’ fo...,en,...,0,0,[],[],https://twitter.com/ExamineCharlott/status/280...,False,NaN,0,NaN,[]
2012-12-17,280900173373259776,280900173373259776,2012-12-17 23:59:54 EST,23:59:54,27587647,mflorcruz,Michelle FlorCruz,NaN,My mental-health follow up to last Friday's sc...,en,...,0,0,"['china', 'sandyhook']",[],https://twitter.com/mflorcruz/status/280900173...,False,NaN,0,NaN,[]
2012-12-17,280900162224787457,280900162224787457,2012-12-17 23:59:52 EST,23:59:52,545623823,joe_strong92,joseph strong,NaN,reading the news reports about sandy hook is q...,en,...,1,0,['cantcomprehend'],[],https://twitter.com/joe_strong92/status/280900...,False,NaN,0,NaN,[]
2012-12-17,280900158449934337,280900158449934337,2012-12-17 23:59:51 EST,23:59:51,63205281,locheikh,Sheikh Ahmadou Bamba,NaN,While witnessing a mass massacre as the one to...,en,...,0,0,[],[],https://twitter.com/locheikh/status/2809001584...,False,NaN,0,NaN,[]
2012-12-17,280900158013714433,280900158013714433,2012-12-17 23:59:51 EST,23:59:51,291406473,bgp516,Marilyn,NaN,President Obama Speaks On The Sandy Hook Shoot...,en,...,0,0,[],[],https://twitter.com/bgp516/status/280900158013...,False,NaN,0,NaN,[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2012-12-12,278880434824286210,278880434824286210,2012-12-12 10:14:11 EST,10:14:11,49660570,gatewaynps,Gateway Natl Rec Area,NaN,Contractors check for unexploded ordnances at ...,en,...,1,0,[],[],https://twitter.com/GatewayNPS/status/27888043...,False,NaN,0,NaN,[]
2012-12-12,278878492194660353,278878492194660353,2012-12-12 10:06:28 EST,10:06:28,52382923,midtowncoffee,Keith N' Kaboodle,"{'type': 'Point', 'coordinates': [40.719735, -...",I'm at Arch - Sandy Hook Conference Room (Jers...,en,...,0,0,[],[],https://twitter.com/MidtownCoffee/status/27887...,False,NaN,0,NaN,[]
2012-12-12,278792261075087360,278792261075087360,2012-12-12 04:23:49 EST,04:23:49,520917926,merrywy1,Merry Segalla,NaN,Sales WGH20226 Sandy Hook Lighthouse Light Vin...,en,...,0,0,['sales'],[],https://twitter.com/Merrywy1/status/2787922610...,False,NaN,0,NaN,[]
2012-12-12,278746542196813824,278746542196813824,2012-12-12 01:22:09 EST,01:22:09,266276765,ushiptxvehicles,uShip TX Vehicles,NaN,"2010 Ford F-150 Lariat: From Mesquite, TX to S...",en,...,0,0,[],[],https://twitter.com/uShipTXVehicles/status/278...,False,NaN,0,NaN,[]
2012-12-12,278741384209518592,278741384209518592,2012-12-12 01:01:39 EST,01:01:39,63904928,shortyconfident,Ta'Kyra R'Reon,NaN,This Nigga said a tall Tee from Hibbets wit th...,en,...,0,0,[],[],https://twitter.com/shortyConfident/status/278...,False,NaN,0,NaN,[]

In [31]:
# group by count to see what sandy hook was to what it became
dates_bet.groupby('date').count()

,id,conversation_id,created_at,time,user_id,username,name,place,tweet,language,...,retweets_count,likes_count,hashtags,cashtags,link,retweet,quote_url,video,thumbnail,reply_to
date,,,,,,,,,,,,,,,,,,,,,
2012-12-12,35,35,35,35,35,35,35,4,35,35,...,35,35,35,35,35,35,0,35,0,35
2012-12-13,29,29,29,29,29,29,29,7,29,29,...,29,29,29,29,29,29,0,29,0,29
2012-12-14,90094,90094,90094,90094,90094,90094,90080,1504,90094,90094,...,90094,90094,90094,90094,90094,90094,11,90094,1373,90094
2012-12-15,49249,49249,49249,49249,49249,49249,49240,746,49249,49249,...,49249,49249,49249,49249,49249,49249,7,49249,1482,49249
2012-12-16,55516,55516,55516,55516,55516,55516,55505,763,55516,55516,...,55516,55516,55516,55516,55516,55516,7,55516,1538,55516
2012-12-17,65816,65816,65816,65816,65816,65816,65807,762,65816,65816,...,65816,65816,65816,65816,65816,65816,5,65816,1394,65816